display_name: LocalDrop
packager: Kuberwastaken
packagerEmail: Kuberwastaken@users.noreply.github.com
url: https://github.com/Kuberwastaken/localdrop
buildArch: x86_64
license: Apache-2.0

icon: assets/img/logo-512.png

requires:
  - libappindicator
  - xdg-user-dirs

keywords:
  - Sharing
  - LAN
  - Files

generic_name: An open source cross-platform alternative to AirDrop
summary: Share files easily with LocalDrop
group: Applications/Utilities

categories:
  - GTK
  - FileTransfer
  - Utility

startup_notify: true
